[package]
version = "0.0.1" # Semantic Versioning is used: https://semver.org/

# These fields are used primarily for display in the extension browser UI.
title = "Chromium Embedded Framework"
description = "Adds Chromium Embedded Framework support for omni.ui"
category = "Other"
keywords = ["cef", "chromium", "webview", "chrome", "ui"]
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
authors = ["Axel Cocat <ax.cocat@gmail.com>"]
repository = "https://github.com/r-o-b-o-t-o/omniverse-cef"

[dependencies]
"omni.ui" = {}

[[python.module]]
name = "r_o_b_o_t_o.cef"

[[native.library]]
path = "bin/${lib_prefix}r_o_b_o_t_o.cef${lib_ext}"

args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]

stdoutFailPatterns.exclude = [
    "*omniclient: Initialization failed*",
]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
cpp_api = [
    "include/CppWidget.h",
]
